name: 'AI inference'

on: workflow_dispatch

jobs:
  inference:
    permissions:
      models: read
    runs-on: ubuntu-latest
    steps:
      - name: AI Inference with GitHub Tools
        id: inference
        uses: actions/ai-inference@v2.0.1
        with:
          prompt: 'List my open pull requests and create a summary'
          enable-github-mcp: true
          token: ${{ secrets.GITHUB_TOKEN }}
          github-mcp-token: ${{ secrets.USER_PAT }}
