name: Draft Release

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/draft-release.yml"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/draft-release.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: |
          echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: draft release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: "master-${{ steps.sha.outputs.short_sha }}"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          overwrite: true
          tag: "master-${{ steps.sha.outputs.short_sha }}"
          # file_glob: true
          file: .
